http:
  port: "8081"
 
sfdc:
  username: "sanju@ust.com"
  password: "Pambrakaran@123"
  token: "q7TuMVbjx1jio6Vhj4C5jvG22"
 
file:
  accountsDir: "/Users/180103/Downloads/APDevFundamentals4.4_studentFiles_SP_05oct2021/resources"

db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"